FROM ruby:2.6.6-alpine

# Build ENV vars
ENV APP_PATH /var/app
ENV BUNDLE_VERSION 2.1.4
ENV BUNDLE_PATH /usr/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_STDOUT true

# Default Rails port
ENV RAILS_PORT 5250

# Copy entrypoint scripts and give execution permissions
COPY ./docker-entrypoint.sh /usr/local/bin/entrypoint.sh
COPY ./test-entrypoint.sh /usr/local/bin/test-entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh && chmod +x /usr/local/bin/test-entrypoint.sh

# System upgrade, setup and tooling
RUN apk --no-cache update \
&& apk --no-cache upgrade \
&& apk add --no-cache \ 
build-base \
python2 \
ttf-ubuntu-font-family \
git \
postgresql-dev \
postgresql-client \
libxml2-dev \
libxslt-dev \
nodejs \
yarn \
imagemagick \
tzdata \
less \
zsh \
sqlite-dev \
npm \
gcompat


# Copy wkhtmltopdf binary with QT patches for Alpine Linux
COPY --from=madnight/docker-alpine-wkhtmltopdf /bin/wkhtmltopdf /bin/wkhtmltopdf

# Clean up and create app dir
RUN rm -rf /var/cache/apk/* \
&& mkdir -p $APP_PATH

# Install bundler
RUN gem install bundler --version "$BUNDLE_VERSION" \
&& rm -rf $GEM_HOME/cache/*

RUN gem install rubygems-update -v 3.4.22
RUN update_rubygems 
RUN gem update --system

# install ember
RUN npm install -g ember-cli

# Change to app dir
WORKDIR $APP_PATH

EXPOSE $RAILS_PORT

ENTRYPOINT [ "bundle", "exec" ]