# DSA Algorithm Seed Data
# This file contains all 30 algorithms from the dsa-training.md organized by phase

ALGORITHMS = [
  # Phase 1: Foundation Patterns
  {
    name: "Two Sum",
    problem_number: 24,
    difficulty: "Easy",
    priority: 1,
    primary_data_structure: "Arrays, Hash Map",
    time_complexity: "O(N²) brute / O(N) optimal",
    space_complexity: "O(1) / O(N)",
    prerequisites: "None",
    visual_complexity: "Low",
    recommended_medium: "Static Infographic",
    estimated_production_time: "2-3 hours",
    key_visual_elements: "Array spotlight, Hash table visualization",
    cognitive_load: "Low",
    real_world_analogy: "Finding matching socks in a drawer",
    learning_domain: "Intellectual Skills",
    learning_phase: 1,
    problem_hook_title: "Two Sum: Find the Perfect Pair",
    problem_hook_analogy: "Like finding matching socks in a drawer - there's a smart way!",
    learning_objective: "Learn how a hash map turns O(N²) into O(N)",
    key_insights: "Trade space (hash map) for time (single pass). Check complement (target - current) not all pairs.",
    practice_challenge: "Three Sum: Find three numbers that sum to target",
    related_algorithms: "Three Sum, Four Sum, Two Sum II"
  },
  {
    name: "Valid Parentheses",
    problem_number: 26,
    difficulty: "Easy",
    priority: 2,
    primary_data_structure: "Stack",
    time_complexity: "O(N)",
    space_complexity: "O(N)",
    prerequisites: "None",
    visual_complexity: "Low",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "3-4 hours",
    key_visual_elements: "Stack growing/shrinking, Bracket matching",
    cognitive_load: "Low",
    real_world_analogy: "Stacking plates",
    learning_domain: "Intellectual Skills",
    learning_phase: 1,
    problem_hook_title: "Valid Parentheses: Balance the Brackets",
    problem_hook_analogy: "Like stacking plates - each opening bracket needs a matching closing one",
    learning_objective: "Master stack-based matching problems",
    key_insights: "Use stack to track opening brackets. Pop on closing bracket. Stack must be empty at end.",
    practice_challenge: "Generate Parentheses: Generate all valid combinations",
    related_algorithms: "Daily Temperatures, Decode String, Basic Calculator"
  },
  {
    name: "Move Zeroes",
    problem_number: 19,
    difficulty: "Easy",
    priority: 3,
    primary_data_structure: "Arrays, Two Pointers",
    time_complexity: "O(N)",
    space_complexity: "O(1)",
    prerequisites: "Arrays basics",
    visual_complexity: "Low",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "2-3 hours",
    key_visual_elements: "Two pointer movement, Swap visualization",
    cognitive_load: "Low",
    real_world_analogy: "Organizing books on a shelf",
    learning_domain: "Intellectual Skills",
    learning_phase: 1,
    problem_hook_title: "Move Zeroes: The Shelf Organizer",
    problem_hook_analogy: "Like moving all empty spaces to the end of a bookshelf",
    learning_objective: "Master two-pointer in-place array manipulation",
    key_insights: "Use two pointers: one for reading, one for writing. Swap non-zero elements forward.",
    practice_challenge: "Remove Element: Remove all instances of a value",
    related_algorithms: "Container With Most Water, Sort Colors"
  },
  {
    name: "Valid Anagram",
    problem_number: 25,
    difficulty: "Easy",
    priority: 4,
    primary_data_structure: "Strings, Hash Map",
    time_complexity: "O(N)",
    space_complexity: "O(K)",
    prerequisites: "None",
    visual_complexity: "Low",
    recommended_medium: "Static Infographic",
    estimated_production_time: "2 hours",
    key_visual_elements: "Character frequency table",
    cognitive_load: "Low",
    real_world_analogy: "Counting letters in Scrabble",
    learning_domain: "Intellectual Skills",
    learning_phase: 1,
    problem_hook_title: "Valid Anagram: The Letter Counter",
    problem_hook_analogy: "Like counting Scrabble tiles - same letters, different arrangement",
    learning_objective: "Master frequency counting patterns",
    key_insights: "Count character frequencies. Two strings are anagrams if frequencies match.",
    practice_challenge: "Group Anagrams: Group strings by anagram signature",
    related_algorithms: "Group Anagrams, Find All Anagrams"
  },
  {
    name: "Best Time to Buy and Sell Stock",
    problem_number: 3,
    difficulty: "Easy",
    priority: 5,
    primary_data_structure: "Arrays",
    time_complexity: "O(N)",
    space_complexity: "O(1)",
    prerequisites: "None",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "3-4 hours",
    key_visual_elements: "Price chart, Min tracker, Profit calculation",
    cognitive_load: "Medium",
    real_world_analogy: "Vegetable market trading",
    learning_domain: "Intellectual Skills",
    learning_phase: 1,
    problem_hook_title: "Stock Trading: Find Maximum Profit",
    problem_hook_analogy: "Like buying vegetables at the morning market and selling at peak price",
    learning_objective: "Learn single-pass optimization with running minimum",
    key_insights: "Track minimum price seen so far. Calculate profit at each step. Keep max profit.",
    practice_challenge: "Best Time to Buy and Sell Stock II: Multiple transactions",
    related_algorithms: "Maximum Subarray, House Robber"
  },

  # Phase 2: Core Patterns
  {
    name: "Container With Most Water",
    problem_number: 8,
    difficulty: "Medium",
    priority: 6,
    primary_data_structure: "Two Pointers",
    time_complexity: "O(N)",
    space_complexity: "O(1)",
    prerequisites: "Two Sum, Move Zeroes",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "4-5 hours",
    key_visual_elements: "Container visualization, Two pointers closing in",
    cognitive_load: "Medium",
    real_world_analogy: "Finding best water container",
    learning_domain: "Intellectual Skills",
    learning_phase: 2
  },
  {
    name: "Product of Array Except Self",
    problem_number: 20,
    difficulty: "Medium",
    priority: 7,
    primary_data_structure: "Arrays",
    time_complexity: "O(N)",
    space_complexity: "O(1)",
    prerequisites: "Arrays basics",
    visual_complexity: "High",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "5-6 hours",
    key_visual_elements: "Prefix/suffix product visualization, Array transformations",
    cognitive_load: "High",
    real_world_analogy: "Group photo multiplication",
    learning_domain: "Intellectual Skills",
    learning_phase: 2
  },
  {
    name: "Group Anagrams",
    problem_number: 12,
    difficulty: "Medium",
    priority: 8,
    primary_data_structure: "Arrays, Strings, Hash Map",
    time_complexity: "O(N*K log K)",
    space_complexity: "O(N*K)",
    prerequisites: "Valid Anagram",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "4-5 hours",
    key_visual_elements: "Signature generation, Hash map grouping",
    cognitive_load: "Medium",
    real_world_analogy: "Sorting words into labeled boxes",
    learning_domain: "Intellectual Skills",
    learning_phase: 2
  },
  {
    name: "Climbing Stairs",
    problem_number: 6,
    difficulty: "Easy",
    priority: 9,
    primary_data_structure: "Dynamic Programming",
    time_complexity: "O(N)",
    space_complexity: "O(1)",
    prerequisites: "None",
    visual_complexity: "Low",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "3-4 hours",
    key_visual_elements: "Staircase, Bottom-up building",
    cognitive_load: "Low",
    real_world_analogy: "Counting paths up stairs",
    learning_domain: "Intellectual Skills",
    learning_phase: 2
  },
  {
    name: "Longest Consecutive Sequence",
    problem_number: 15,
    difficulty: "Medium",
    priority: 10,
    primary_data_structure: "Arrays, Hash Set",
    time_complexity: "O(N)",
    space_complexity: "O(N)",
    prerequisites: "Valid Anagram",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "4-5 hours",
    key_visual_elements: "Number chains, Hash set lookups",
    cognitive_load: "Medium",
    real_world_analogy: "Finding number chains in a bag",
    learning_domain: "Intellectual Skills",
    learning_phase: 2
  },

  # Phase 3: Stack Mastery
  {
    name: "Daily Temperatures",
    problem_number: 5,
    difficulty: "Medium",
    priority: 11,
    primary_data_structure: "Stack",
    time_complexity: "O(N)",
    space_complexity: "O(N)",
    prerequisites: "Valid Parentheses",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "4-5 hours",
    key_visual_elements: "Stack as waiting list, Temperature comparisons",
    cognitive_load: "Medium",
    real_world_analogy: "Waiting list management",
    learning_domain: "Intellectual Skills",
    learning_phase: 3
  },
  {
    name: "Decode String",
    problem_number: 9,
    difficulty: "Medium",
    priority: 12,
    primary_data_structure: "Stack",
    time_complexity: "O(N*M)",
    space_complexity: "O(N)",
    prerequisites: "Valid Parentheses",
    visual_complexity: "High",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "5-6 hours",
    key_visual_elements: "Nested stack operations, String building",
    cognitive_load: "High",
    real_world_analogy: "Nested folders unpacking",
    learning_domain: "Intellectual Skills",
    learning_phase: 3
  },
  {
    name: "Basic Calculator",
    problem_number: 2,
    difficulty: "Hard",
    priority: 13,
    primary_data_structure: "Stack",
    time_complexity: "O(N)",
    space_complexity: "O(N)",
    prerequisites: "Valid Parentheses, Decode String",
    visual_complexity: "High",
    recommended_medium: "Interactive Simulation",
    estimated_production_time: "6-8 hours",
    key_visual_elements: "Stack for sub-expressions, PEMDAS visualization",
    cognitive_load: "High",
    real_world_analogy: "Following recipe order",
    learning_domain: "Intellectual Skills",
    learning_phase: 3
  },

  # Phase 4: Binary Search
  {
    name: "Find First and Last Position",
    problem_number: 10,
    difficulty: "Medium",
    priority: 14,
    primary_data_structure: "Binary Search",
    time_complexity: "O(log N)",
    space_complexity: "O(1)",
    prerequisites: "None",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "4-5 hours",
    key_visual_elements: "Binary search split, Left/right boundary finding",
    cognitive_load: "Medium",
    real_world_analogy: "Dictionary word range finding",
    learning_domain: "Intellectual Skills",
    learning_phase: 4
  },
  {
    name: "Find Peak Element",
    problem_number: 11,
    difficulty: "Medium",
    priority: 15,
    primary_data_structure: "Binary Search",
    time_complexity: "O(log N)",
    space_complexity: "O(log N)",
    prerequisites: "Find First and Last",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "4-5 hours",
    key_visual_elements: "Peak detection, Binary search slopes",
    cognitive_load: "Medium",
    real_world_analogy: "Finding hill peaks",
    learning_domain: "Intellectual Skills",
    learning_phase: 4
  },
  {
    name: "Median of Two Sorted Arrays",
    problem_number: 17,
    difficulty: "Hard",
    priority: 16,
    primary_data_structure: "Binary Search",
    time_complexity: "O(log(min(M,N)))",
    space_complexity: "O(1)",
    prerequisites: "Binary Search mastery",
    visual_complexity: "Very High",
    recommended_medium: "Interactive Simulation",
    estimated_production_time: "8-10 hours",
    key_visual_elements: "Partition visualization, Left/right halves",
    cognitive_load: "Very High",
    real_world_analogy: "Cutting two sorted lists",
    learning_domain: "Intellectual Skills",
    learning_phase: 4
  },

  # Phase 5: Dynamic Programming
  {
    name: "Coin Change",
    problem_number: 7,
    difficulty: "Medium",
    priority: 17,
    primary_data_structure: "Dynamic Programming",
    time_complexity: "O(S*N)",
    space_complexity: "O(S)",
    prerequisites: "Climbing Stairs",
    visual_complexity: "High",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "5-6 hours",
    key_visual_elements: "DP table building, Coin selection",
    cognitive_load: "High",
    real_world_analogy: "Making change efficiently",
    learning_domain: "Intellectual Skills",
    learning_phase: 5
  },
  {
    name: "House Robber",
    problem_number: 13,
    difficulty: "Medium",
    priority: 18,
    primary_data_structure: "Dynamic Programming",
    time_complexity: "O(2^N) brute / O(N) optimal",
    space_complexity: "O(N) / O(1)",
    prerequisites: "Climbing Stairs",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "4-5 hours",
    key_visual_elements: "Decision tree, DP state transitions",
    cognitive_load: "Medium",
    real_world_analogy: "Robbing non-adjacent houses",
    learning_domain: "Intellectual Skills",
    learning_phase: 5
  },
  {
    name: "Word Break",
    problem_number: 28,
    difficulty: "Medium",
    priority: 19,
    primary_data_structure: "Dynamic Programming",
    time_complexity: "O(N²)",
    space_complexity: "O(N)",
    prerequisites: "Climbing Stairs, Coin Change",
    visual_complexity: "High",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "5-6 hours",
    key_visual_elements: "DP buildable array, Dictionary lookups",
    cognitive_load: "High",
    real_world_analogy: "Breaking strings into words",
    learning_domain: "Intellectual Skills",
    learning_phase: 5
  },
  {
    name: "Jump Game II",
    problem_number: 14,
    difficulty: "Medium",
    priority: 20,
    primary_data_structure: "Greedy, Arrays",
    time_complexity: "O(N)",
    space_complexity: "O(1)",
    prerequisites: "Best Time to Buy/Sell Stock",
    visual_complexity: "High",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "5-6 hours",
    key_visual_elements: "Jump windows, Farthest reach tracking",
    cognitive_load: "High",
    real_world_analogy: "Board game optimal jumps",
    learning_domain: "Intellectual Skills",
    learning_phase: 5
  },

  # Phase 6: Advanced Structures
  {
    name: "Add Two Numbers",
    problem_number: 1,
    difficulty: "Medium",
    priority: 21,
    primary_data_structure: "Linked Lists",
    time_complexity: "O(max(N,M))",
    space_complexity: "O(max(N,M))",
    prerequisites: "None",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "4-5 hours",
    key_visual_elements: "Linked list traversal, Carry visualization",
    cognitive_load: "Medium",
    real_world_analogy: "Elementary school addition",
    learning_domain: "Intellectual Skills",
    learning_phase: 6
  },
  {
    name: "Merge Intervals",
    problem_number: 18,
    difficulty: "Medium",
    priority: 22,
    primary_data_structure: "Arrays, Sorting",
    time_complexity: "O(N log N)",
    space_complexity: "O(N)",
    prerequisites: "None",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "4-5 hours",
    key_visual_elements: "Interval timeline, Merge operations",
    cognitive_load: "Medium",
    real_world_analogy: "Calendar meeting consolidation",
    learning_domain: "Intellectual Skills",
    learning_phase: 6
  },
  {
    name: "LRU Cache",
    problem_number: 16,
    difficulty: "Medium",
    priority: 23,
    primary_data_structure: "Hash Map, Doubly Linked List",
    time_complexity: "O(1)",
    space_complexity: "O(C)",
    prerequisites: "Linked Lists basics",
    visual_complexity: "Very High",
    recommended_medium: "Interactive Simulation",
    estimated_production_time: "8-10 hours",
    key_visual_elements: "Hash map + list combo, LRU eviction",
    cognitive_load: "Very High",
    real_world_analogy: "Bookshelf organization",
    learning_domain: "Intellectual Skills",
    learning_phase: 6
  },
  {
    name: "Top K Frequent Elements",
    problem_number: 22,
    difficulty: "Medium",
    priority: 24,
    primary_data_structure: "Arrays, Hash Map",
    time_complexity: "O(N + U log U)",
    space_complexity: "O(U)",
    prerequisites: "Valid Anagram",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "4-5 hours",
    key_visual_elements: "Frequency counting, Top K selection",
    cognitive_load: "Medium",
    real_world_analogy: "Finding most popular items",
    learning_domain: "Intellectual Skills",
    learning_phase: 6
  },

  # Phase 7: Complex Algorithms
  {
    name: "Trapping Rain Water",
    problem_number: 23,
    difficulty: "Hard",
    priority: 25,
    primary_data_structure: "Arrays, Two Pointers, DP",
    time_complexity: "O(N)",
    space_complexity: "O(N)",
    prerequisites: "Container With Most Water",
    visual_complexity: "Very High",
    recommended_medium: "Interactive Simulation",
    estimated_production_time: "8-10 hours",
    key_visual_elements: "Elevation map, Water filling, Left/right max",
    cognitive_load: "Very High",
    real_world_analogy: "Landscape water retention",
    learning_domain: "Intellectual Skills",
    learning_phase: 7
  },
  {
    name: "Candy",
    problem_number: 4,
    difficulty: "Hard",
    priority: 26,
    primary_data_structure: "Arrays, Greedy",
    time_complexity: "O(N)",
    space_complexity: "O(N)",
    prerequisites: "None",
    visual_complexity: "High",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "5-6 hours",
    key_visual_elements: "Two-pass visualization, Candy distribution",
    cognitive_load: "High",
    real_world_analogy: "Fair candy allocation",
    learning_domain: "Intellectual Skills",
    learning_phase: 7
  },
  {
    name: "Sort Colors",
    problem_number: 21,
    difficulty: "Medium",
    priority: 27,
    primary_data_structure: "Two Pointers",
    time_complexity: "O(N)",
    space_complexity: "O(1)",
    prerequisites: "Move Zeroes",
    visual_complexity: "Medium",
    recommended_medium: "Animated Explainer",
    estimated_production_time: "4-5 hours",
    key_visual_elements: "Three-way partition, Dutch flag",
    cognitive_load: "Medium",
    real_world_analogy: "Sorting colored marbles",
    learning_domain: "Intellectual Skills",
    learning_phase: 7
  },
  {
    name: "Valid Sudoku",
    problem_number: 27,
    difficulty: "Medium",
    priority: 28,
    primary_data_structure: "Arrays",
    time_complexity: "O(1)",
    space_complexity: "O(1)",
    prerequisites: "None",
    visual_complexity: "Medium",
    recommended_medium: "Static Infographic",
    estimated_production_time: "3-4 hours",
    key_visual_elements: "Grid validation, Row/col/box checks",
    cognitive_load: "Medium",
    real_world_analogy: "Sudoku rule checking",
    learning_domain: "Intellectual Skills",
    learning_phase: 7
  },
  {
    name: "Word Ladder",
    problem_number: 29,
    difficulty: "Hard",
    priority: 29,
    primary_data_structure: "BFS, Queue, Graph",
    time_complexity: "O(M²*N)",
    space_complexity: "O(M*N)",
    prerequisites: "Valid Parentheses (Queue)",
    visual_complexity: "Very High",
    recommended_medium: "Interactive Simulation",
    estimated_production_time: "8-10 hours",
    key_visual_elements: "BFS wave expansion, Word graph",
    cognitive_load: "Very High",
    real_world_analogy: "Word transformation puzzle",
    learning_domain: "Intellectual Skills",
    learning_phase: 7
  },
  {
    name: "Word Search",
    problem_number: 30,
    difficulty: "Medium",
    priority: 30,
    primary_data_structure: "DFS, Backtracking",
    time_complexity: "O(N*3^L)",
    space_complexity: "O(L)",
    prerequisites: "None",
    visual_complexity: "High",
    recommended_medium: "Interactive Simulation",
    estimated_production_time: "6-8 hours",
    key_visual_elements: "Grid traversal, Backtracking visualization",
    cognitive_load: "High",
    real_world_analogy: "Newspaper word search",
    learning_domain: "Intellectual Skills",
    learning_phase: 7
  }
]

# Learning phases metadata
LEARNING_PHASES = [
  {
    phase_number: 1,
    name: "Foundation Patterns",
    focus_area: "Basic array manipulation and simple data structures",
    key_learning_goal: "Master basic array manipulation and simple data structures",
    algorithm_count: 5
  },
  {
    phase_number: 2,
    name: "Core Patterns",
    focus_area: "Optimization patterns and DP introduction",
    key_learning_goal: "Understand optimization patterns and DP introduction",
    algorithm_count: 5
  },
  {
    phase_number: 3,
    name: "Stack Mastery",
    focus_area: "Stack-based problem solving",
    key_learning_goal: "Master stack-based problem solving",
    algorithm_count: 3
  },
  {
    phase_number: 4,
    name: "Binary Search",
    focus_area: "Binary search variations",
    key_learning_goal: "Master binary search variations",
    algorithm_count: 3
  },
  {
    phase_number: 5,
    name: "Dynamic Programming",
    focus_area: "DP patterns and greedy algorithms",
    key_learning_goal: "Master DP patterns and greedy algorithms",
    algorithm_count: 4
  },
  {
    phase_number: 6,
    name: "Advanced Structures",
    focus_area: "Complex data structures",
    key_learning_goal: "Work with complex data structures",
    algorithm_count: 4
  },
  {
    phase_number: 7,
    name: "Complex Algorithms",
    focus_area: "Sophisticated multi-concept problems",
    key_learning_goal: "Tackle sophisticated multi-concept problems",
    algorithm_count: 6
  }
]
