production:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') { 'foobar' } %>

staging:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') { 'foobar' } %>

test:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') { 'foobar' } %>
