:verbose: false
:concurrency: 1
:max_retries: 3
:timeout: 8
:logfile: ./log/sidekiq.log
:queues:
  - critical
  - mailers
  - default
  - action_mailbox_routing
  - action_mailbox_incineration
  - active_storage_analysis
  - active_storage_purge
  - low
  - ahoy
